BEGIN {
	mysym=ENVIRON["IFDEFSYM"];
	hadone=0;
	copy=1;
	print "#if 0";
	print "# this file is automatically generated.";
	print "# please edit the master and rerun ./configure.";
	print "#endif";
	print "";
}

{
	if ( $1 == "#ifdef" ) {
		if ( $2 == mysym ) {
			copy=1;
			hadone=1;
		} else {
			copy=0;
		}
	} else if ( $1 == "#elifdef" ) {
		if ( copy == 0 ) {
			if ( $2 == mysym ) {
				copy=1;
				hadone=1;
			} else {
				copy=0;
			}
		} else {
			copy=0;
		}
	} else if ( $1 == "#else" ) {
		if ( copy ) {
			copy=0;
		} else {
			if ( hadone )  copy=0;
			else           copy=1;
		}
	} else if ( $1 == "#ifndef" ) {
		if ( $2 == mysym ) {
			copy=0;
			hadone=1;
		} else {
			copy=1;
			hadone=1;
		}
	} else if ( $1 == "#endif" ) {
		copy=1;
		hadone=0;
	} else
		if ( copy )      print;
}

END {
}
