# Configuration file for PfkAppLauncher

[Global]
rows = 1
columns = 3
icon_size = 96
window_x = 1500
window_y = 800
minimize_on_launch = false
bgcolor=#203040
textcolor=#ffffff
highlight_color=#406080

# --- Application Slots ---
# Define each application in a section named Slot_ROW_COLUMN, starting from 0.
# For example, Slot_0_0 is the top-left item.

# Example for Windows (Notepad)
#[Slot_0_0]
#title = Notepad
## You can often use the executable itself as the icon source for .exe files.
#icon = %SystemRoot%\System32\notepad.exe
#executable = notepad.exe

# Example for Windows (Calculator)
#[Slot_0_1]
#title = Calculator
# You can also use PNG files.
#icon = C:\path\to\your\icons\calculator.png
#executable = calc.exe

# Example for Linux (Terminal)
[Slot_0_0]
title = pfkterm
icon = /usr/share/icons/gnome/48x48/apps/utilities-terminal.png
executable = pfkterm

# Example for Linux (Terminal)
[Slot_0_1]
title = Gnome-Terminal
icon = /usr/share/icons/gnome/48x48/apps/utilities-terminal.png
executable = gnome-terminal

# Example for Linux (Firefox)
[Slot_0_2]
title = Firefox
icon = /usr/share/icons/hicolor/48x48/apps/firefox.png
executable = firefox
