# Configuration file for PfkAppLauncher

[Global]
rows = 1
columns = 2
icon_size = 96
window_x = 100
window_y = 20
minimize_on_launch = false
bgcolor=#203040
textcolor=#ffffff
highlight_color=#406080

# --- Application Slots ---
# Define each application in a section named Slot_ROW_COLUMN, starting from 0.
# For example, Slot_0_0 is the top-left item.

# Example for Windows (Notepad)
[Slot_0_0]
title = Notepad++
icon = notepad++.png
executable = C:\Users\pknaack1\data\apps\Notepad++\notepad++.exe

[Slot_0_1]
title = GMAIL
# i found this in 'c:/Users/pknaack1/AppData/Local/Google/Chrome/User Data/Profile 3/Web Applications/Manifest Resources'
icon = Gmail.png
executable = "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=fmgjjmmmlfnkbppncabfkddbjimcfncm


#calendar "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep
#chat "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi
#drive "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=aghbiahbpaijignceidepookljebhfak
#docs "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=mpnpojknpmmopombnjdcgaaiekajbnjb
#sheets "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=fhihpiojkbmbpdjeoajapmgkhlnakfjf
#chrome "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory="Default"
#gemini "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=gdfaincndogidkdcdkhapmbffkckdkhn
#notebooklm "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=gdfaincndogidkdcdkhapmbffkckdkhn

#gmail "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=fmgjjmmmlfnkbppncabfkddbjimcfncm
#calendar "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep
#chat "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi
#drive "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=mdpkiolbdkhdjpekfbkbmhigcaggjagi
#docs "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=mpnpojknpmmopombnjdcgaaiekajbnjb
#sheets "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=fhihpiojkbmbpdjeoajapmgkhlnakfjf
#chrome "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 3"
#gemini "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=gdfaincndogidkdcdkhapmbffkckdkhn
#notebooklm "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 3" --app-id=gjcmcplpgihbecacndmmbaenpfgimlec
