/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/*
 * NOTE: THIS FILE IS NOT IDENTICAL TO THAT PRODUCED BY 'rpcgen'.
 *       IT HAS BEEN EDITED FOR TYPEDEFS AND PROTOTYPES TO BE COMPATIBLE
 *       WITH THE NFS SERVER FRAMEWORK.
 */

#include "nfs_prot.h"

bool_t
myxdr_nfsstat(register XDR *xdrs, nfsstat *objp)
{
    return myxdr_enum(xdrs, (enum_t *)objp);
}

bool_t
myxdr_ftype(register XDR *xdrs, ftype *objp)
{
    return myxdr_enum(xdrs, (enum_t *)objp);
}

bool_t
myxdr_nfs_fh(register XDR *xdrs, nfs_fh *objp)
{
    return myxdr_opaque(xdrs, objp->data, NFS_FHSIZE);
}

bool_t
myxdr_nfstime(register XDR *xdrs, nfstime *objp)
{
    if (!myxdr_u_int(xdrs, &objp->seconds))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->useconds))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_fattr(register XDR *xdrs, fattr *objp)
{
    if (!myxdr_ftype(xdrs, &objp->type))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->mode))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->nlink))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->uid))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->gid))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->size))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->blocksize))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->rdev))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->blocks))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->fsid))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->fileid))
        return (FALSE);
    if (!myxdr_nfstime(xdrs, &objp->atime))
        return (FALSE);
    if (!myxdr_nfstime(xdrs, &objp->mtime))
        return (FALSE);
    if (!myxdr_nfstime(xdrs, &objp->ctime))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_sattr(register XDR *xdrs, sattr *objp)
{
    if (!myxdr_u_int(xdrs, &objp->mode))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->uid))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->gid))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->size))
        return (FALSE);
    if (!myxdr_nfstime(xdrs, &objp->atime))
        return (FALSE);
    if (!myxdr_nfstime(xdrs, &objp->mtime))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_filename(register XDR *xdrs, filename *objp)
{
    if (!myxdr_string(xdrs, objp, NFS_MAXNAMLEN))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_nfspath(register XDR *xdrs, nfspath *objp)
{
    if (!myxdr_string(xdrs, objp, NFS_MAXPATHLEN))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_attrstat(register XDR *xdrs, attrstat *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_fattr(xdrs, &objp->attrstat_u.attributes))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}

bool_t
myxdr_sattrargs(register XDR *xdrs, sattrargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->file))
        return (FALSE);
    if (!myxdr_sattr(xdrs, &objp->attributes))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_diropargs(register XDR *xdrs, diropargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->dir))
        return (FALSE);
    if (!myxdr_filename(xdrs, &objp->name))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_diropokres(register XDR *xdrs, diropokres *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->file))
        return (FALSE);
    if (!myxdr_fattr(xdrs, &objp->attributes))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_diropres(register XDR *xdrs, diropres *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_diropokres(xdrs, &objp->diropres_u.diropres))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}

bool_t
myxdr_readlinkres(register XDR *xdrs, readlinkres *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_nfspath(xdrs, &objp->readlinkres_u.data))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}

bool_t
myxdr_readargs(register XDR *xdrs, readargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->file))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->offset))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->count))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->totalcount))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_readokres(register XDR *xdrs, readokres *objp)
{
    if (!myxdr_fattr(xdrs, &objp->attributes))
        return (FALSE);
    if (!myxdr_bytes(xdrs,
                   (uchar **)&objp->data.data_val,
                   (u_int *) &objp->data.data_len, NFS_MAXDATA))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_readres(register XDR *xdrs, readres *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_readokres(xdrs, &objp->readres_u.reply))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}

bool_t
myxdr_writeargs(register XDR *xdrs, writeargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->file))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->beginoffset))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->offset))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->totalcount))
        return (FALSE);
    if (!myxdr_bytes(xdrs,
                   (uchar **)&objp->data.data_val,
                   (u_int *) &objp->data.data_len, NFS_MAXDATA))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_createargs(register XDR *xdrs, createargs *objp)
{
    if (!myxdr_diropargs(xdrs, &objp->where))
        return (FALSE);
    if (!myxdr_sattr(xdrs, &objp->attributes))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_renameargs(register XDR *xdrs, renameargs *objp)
{
    if (!myxdr_diropargs(xdrs, &objp->from))
        return (FALSE);
    if (!myxdr_diropargs(xdrs, &objp->to))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_linkargs(register XDR *xdrs, linkargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->from))
        return (FALSE);
    if (!myxdr_diropargs(xdrs, &objp->to))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_symlinkargs(register XDR *xdrs, symlinkargs *objp)
{
    if (!myxdr_diropargs(xdrs, &objp->from))
        return (FALSE);
    if (!myxdr_nfspath(xdrs, &objp->to))
        return (FALSE);
    if (!myxdr_sattr(xdrs, &objp->attributes))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_nfscookie(register XDR *xdrs, nfscookie objp)
{
    if (!myxdr_opaque(xdrs, objp, NFS_COOKIESIZE))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_readdirargs(register XDR *xdrs, readdirargs *objp)
{
    if (!myxdr_nfs_fh(xdrs, &objp->dir))
        return (FALSE);
    if (!myxdr_nfscookie(xdrs, objp->cookie))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->count))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_entry(register XDR *xdrs, entry *objp)
{
    if (!myxdr_u_int(xdrs, &objp->fileid))
        return (FALSE);
    if (!myxdr_filename(xdrs, &objp->name))
        return (FALSE);
    if (!myxdr_nfscookie(xdrs, objp->cookie))
        return (FALSE);
    if (!myxdr_pointer(xdrs,
                     (uchar **)&objp->nextentry,
                     sizeof (entry), (xdrproc_t) myxdr_entry))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_dirlist(register XDR *xdrs, dirlist *objp)
{
    if (!myxdr_pointer(xdrs,
                     (uchar **)&objp->entries,
                     sizeof (entry), (xdrproc_t) myxdr_entry))
        return (FALSE);
    if (!myxdr_bool(xdrs, &objp->eof))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_readdirres(register XDR *xdrs, readdirres *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_dirlist(xdrs, &objp->readdirres_u.reply))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}

bool_t
myxdr_statfsokres(register XDR *xdrs, statfsokres *objp)
{
    if (!myxdr_u_int(xdrs, &objp->tsize))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->bsize))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->blocks))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->bfree))
        return (FALSE);
    if (!myxdr_u_int(xdrs, &objp->bavail))
        return (FALSE);
    return (TRUE);
}

bool_t
myxdr_statfsres(register XDR *xdrs, statfsres *objp)
{
    if (!myxdr_nfsstat(xdrs, &objp->status))
        return (FALSE);
    switch (objp->status) {
    case NFS_OK:
        if (!myxdr_statfsokres(xdrs, &objp->statfsres_u.reply))
            return (FALSE);
        break;
    default:
        break;
    }
    return (TRUE);
}
