
/*
    This file is part of the "pfkutils" tools written by Phil Knaack
    (pfk@pfk.org).
    Copyright (C) 2008  Phillip F Knaack

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <stdio.h>

int
main(int argc, char ** argv)
{
    int NUM;
    int i, x, y, z;
    srandom(getpid() * time(0));

    if (argc != 2)
    {
    usage:
        printf("gen_test_points <num>\n");
        return 1;
    }

    NUM = atoi(argv[1]);

    printf("/* this file autogenerated by gen_test_points.c */\n");
    printf("#define NUM_COORDS %d\n", NUM);
    printf("Point test_points[%d] = {\n", NUM);

    for (i=0; i < NUM; i++)
    {
        x = random() % 100;
        y = random() % 100;
        z = random() % 100;
        
        printf("    { %d.%d, %d.%d, %d.%d }%s\n",
               x/10, x%10, y/10, y%10, z/10, z%10,
               (i != (NUM-1)) ? "," : "");
    }

    printf("};\n");
    return 0;
}
