 { 1 , "HUP", "Hangup" },
 { 2 , "INT", "Interrupt" },
 { 3 , "QUIT", "Quit" },
 { 4 , "ILL", "Illegal instruction" },
 { 5 , "TRAP", "Trace trap" },
 { 6 , "ABRT", "Abort" },
 { 7 , "BUS", "Bus error" },
 { 8 , "FPE", "Floating point exception" },
 { 9 , "KILL", "Killed" },
 { 10 , "USR1", "User defined signal 1" },
 { 11 , "SEGV", "Memory fault" },
 { 12 , "USR2", "User defined signal 2" },
 { 13 , "PIPE", "Broken pipe" },
 { 14 , "ALRM", "Alarm clock" },
 { 15 , "TERM", "Terminated" },
 { 16 , "STKFLT", "Stack fault" },
 { 17 , "CHLD", "Child exited" },
 { 18 , "CONT", "Continued" },
 { 19 , "STOP", "Stopped (signal)" },
 { 20 , "TSTP", "Stopped" },
 { 21 , "TTIN", "Stopped (tty input)" },
 { 22 , "TTOU", "Stopped (tty output)" },
 { 23 , "URG", "Urgent I/O condition" },
 { 24 , "XCPU", "CPU time limit exceeded" },
 { 25 , "XFSZ", "File size limit exceeded" },
 { 26 , "VTALRM", "Virtual timer expired" },
 { 27 , "PROF", "Profiling timer expired" },
 { 28 , "WINCH", "Window size change" },
 { 29 , "IO", "I/O possible" },
 { 30 , "PWR", "Power-fail/Restart" },
 { 31 , "UNUSED", "Unused" },
	{ 32 , (char *) 0, "Signal 32" } ,
	{ 33 , (char *) 0, "Signal 33" } ,
	{ 34 , (char *) 0, "Signal 34" } ,
	{ 35 , (char *) 0, "Signal 35" } ,
	{ 36 , (char *) 0, "Signal 36" } ,
	{ 37 , (char *) 0, "Signal 37" } ,
	{ 38 , (char *) 0, "Signal 38" } ,
	{ 39 , (char *) 0, "Signal 39" } ,
	{ 40 , (char *) 0, "Signal 40" } ,
	{ 41 , (char *) 0, "Signal 41" } ,
	{ 42 , (char *) 0, "Signal 42" } ,
	{ 43 , (char *) 0, "Signal 43" } ,
	{ 44 , (char *) 0, "Signal 44" } ,
	{ 45 , (char *) 0, "Signal 45" } ,
	{ 46 , (char *) 0, "Signal 46" } ,
	{ 47 , (char *) 0, "Signal 47" } ,
	{ 48 , (char *) 0, "Signal 48" } ,
	{ 49 , (char *) 0, "Signal 49" } ,
	{ 50 , (char *) 0, "Signal 50" } ,
	{ 51 , (char *) 0, "Signal 51" } ,
	{ 52 , (char *) 0, "Signal 52" } ,
	{ 53 , (char *) 0, "Signal 53" } ,
	{ 54 , (char *) 0, "Signal 54" } ,
	{ 55 , (char *) 0, "Signal 55" } ,
	{ 56 , (char *) 0, "Signal 56" } ,
	{ 57 , (char *) 0, "Signal 57" } ,
	{ 58 , (char *) 0, "Signal 58" } ,
	{ 59 , (char *) 0, "Signal 59" } ,
	{ 60 , (char *) 0, "Signal 60" } ,
	{ 61 , (char *) 0, "Signal 61" } ,
	{ 62 , (char *) 0, "Signal 62" } ,
	{ 63 , (char *) 0, "Signal 63" } ,
	{ 64 , (char *) 0, "Signal 64" } ,
