#!/bin/sh

# be aware that /bin/sh is bash on fedora, but dash on ubuntu!
# this means things like PATH wont be set up on ubuntu! gross!

cd $HOME
ENV=$HOME/.kshrc
export ENV
PATH=$HOME/pfk/bin:$PATH
export PATH

xset +fp $HOME/pfk/fonts
xrdb -load .Xresources
set-background.sh

if [ -f $HOME/safe-session ] ; then
    urxvt -fn fixed -fb fixed || gnome-terminal || xfce4-terminal || xterm
else
    # for safety's sake on that network where it is hard to get to
    # console, make it so there's a way to fix it if it's busted.
#    urxvt -fn fixed -fb fixed || gnome-terminal || xfce4-terminal || xterm
    ssh-agent pfkSessionMgr -s fluxbox pfkSessionXrandr 'set-background.sh wait'
    # when the user "logs out" (pfkSessionMgr -c stop) the vnc will be killed.
fi
vncserver -kill $DISPLAY
exit 0
