#!/bin/sh

cd $HOME
ENV=$HOME/.kshrc
export ENV

if [ -f $HOME/safe-session ] ; then
    urxvt -fn fixed -fb fixed
    gnome-terminal
    xfce4-terminal
    xterm
    exit 0
else
    xset +fp $HOME/pfk/fonts
    xrdb -load .Xresources
    set-background.sh
    exec ssh-agent pfkSessionMgr -s fluxbox pfkSessionXrandr 'set-background.sh wait'
fi
