#!/bin/sh

# since this script is started by lightdm or gdm/xdm, my environment
# will not be set. i need a few basic things, like PFKARCH and SHELL.

cd $HOME
PFKARCH=`$HOME/pfk/bin/architecture`
SHELL=$HOME/pfk/$PFKARCH/bin/pfksh
ENV=$HOME/.kshrc
export ENV PFKARCH SHELL

xrdb -load .Xresources
$HOME/pfk/bin/set-background.sh
exec ssh-agent pfkSessionMgr -s fluxbox
