
complete -c i2 -s i --description "redirect fd0 to specified input file"
complete -c i2 -s o --description "redirect fd1 to specified output file"
complete -c i2 -o Ir --description "input is random data"
complete -c i2 -o Iz --description "input is zero data"
complete -c i2 -s O --description "discard output data"
complete -c i2 -s m --description "max output file size in bytes (rollover)"
complete -c i2 -s n --description "do not read from stdin"
complete -c i2 -s s --description "display stats at end"
complete -c i2 -s p --description "num,num: pause x bytes y microseconds"
complete -c i2 -s v --description "verbose stats, implies -s"
complete -c i2 -o zr --description "uncompress data from network to output"
complete -c i2 -o zt --description "compress input data to network"
complete -c i2 -s d --description "debug mode"
complete -c i2 -s D --description "log data transferred"
complete -c i2 -s f --description "forward local port to remote host/port"
