#!/bin/sh

# args: source_dir  [file...]

source_dir=$1
shift

for f in $* ; do
    if [ ! -f $f ] ; then
	echo new: $f
        cp $source_dir/$f $f
    else
	if ! cmp -s $source_dir/$f $f ; then
	    echo changed: $f
	    cp $source_dir/$f $f
	fi
    fi
done
