# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MyFS.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MyFS.proto',
  package='MyFS',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nMyFS.proto\x12\x04MyFS\"\'\n\x05Login\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\",\n\tLoginResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x1a\n\x07ListDir\x12\x0f\n\x07\x64irname\x18\x01 \x01(\t\"N\n\x08\x44irEntry\x12\x12\n\nentry_name\x18\x01 \x01(\t\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.MyFS.DirEntryType\x12\x0c\n\x04size\x18\x03 \x01(\x05\"O\n\x0bListDirResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.MyFS.DirEntry\"\x1f\n\x0bRequestFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"B\n\x11RequestFileStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x05\"D\n\x0c\x46ileContents\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x94\x01\n\rClient2Server\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.MyFS.MessageType\x12\x1a\n\x05login\x18\x02 \x01(\x0b\x32\x0b.MyFS.Login\x12&\n\x0brequestfile\x18\x03 \x01(\x0b\x32\x11.MyFS.RequestFile\x12\x1e\n\x07listdir\x18\x04 \x01(\x0b\x32\r.MyFS.ListDir\"\xda\x01\n\rServer2Client\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.MyFS.MessageType\x12\"\n\tloginresp\x18\x02 \x01(\x0b\x32\x0f.MyFS.LoginResp\x12\x32\n\x11requestfilestatus\x18\x03 \x01(\x0b\x32\x17.MyFS.RequestFileStatus\x12(\n\x0c\x66ilecontents\x18\x04 \x01(\x0b\x32\x12.MyFS.FileContents\x12&\n\x0blistdirresp\x18\x05 \x01(\x0b\x32\x11.MyFS.ListDirResp*\x87\x01\n\x0bMessageType\x12\t\n\x05LOGIN\x10\x01\x12\x0e\n\nLOGIN_RESP\x10\x02\x12\x0c\n\x08LIST_DIR\x10\x03\x12\x11\n\rLIST_DIR_RESP\x10\x04\x12\x10\n\x0cREQUEST_FILE\x10\x05\x12\x17\n\x13REQUEST_FILE_STATUS\x10\x06\x12\x11\n\rFILE_CONTENTS\x10\x07*+\n\x0c\x44irEntryType\x12\r\n\tTYPE_FILE\x10\x01\x12\x0c\n\x08TYPE_DIR\x10\x02'
)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MyFS.MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_RESP', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIST_DIR', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIST_DIR_RESP', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_FILE', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_FILE_STATUS', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE_CONTENTS', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=840,
  serialized_end=975,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_DIRENTRYTYPE = _descriptor.EnumDescriptor(
  name='DirEntryType',
  full_name='MyFS.DirEntryType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_FILE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_DIR', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=977,
  serialized_end=1020,
)
_sym_db.RegisterEnumDescriptor(_DIRENTRYTYPE)

DirEntryType = enum_type_wrapper.EnumTypeWrapper(_DIRENTRYTYPE)
LOGIN = 1
LOGIN_RESP = 2
LIST_DIR = 3
LIST_DIR_RESP = 4
REQUEST_FILE = 5
REQUEST_FILE_STATUS = 6
FILE_CONTENTS = 7
TYPE_FILE = 1
TYPE_DIR = 2



_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='MyFS.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='MyFS.Login.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='MyFS.Login.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)


_LOGINRESP = _descriptor.Descriptor(
  name='LoginResp',
  full_name='MyFS.LoginResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MyFS.LoginResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='MyFS.LoginResp.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=105,
)


_LISTDIR = _descriptor.Descriptor(
  name='ListDir',
  full_name='MyFS.ListDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dirname', full_name='MyFS.ListDir.dirname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=133,
)


_DIRENTRY = _descriptor.Descriptor(
  name='DirEntry',
  full_name='MyFS.DirEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_name', full_name='MyFS.DirEntry.entry_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='MyFS.DirEntry.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='MyFS.DirEntry.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=213,
)


_LISTDIRRESP = _descriptor.Descriptor(
  name='ListDirResp',
  full_name='MyFS.ListDirResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MyFS.ListDirResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='MyFS.ListDirResp.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='MyFS.ListDirResp.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=294,
)


_REQUESTFILE = _descriptor.Descriptor(
  name='RequestFile',
  full_name='MyFS.RequestFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='MyFS.RequestFile.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=327,
)


_REQUESTFILESTATUS = _descriptor.Descriptor(
  name='RequestFileStatus',
  full_name='MyFS.RequestFileStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MyFS.RequestFileStatus.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='MyFS.RequestFileStatus.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='MyFS.RequestFileStatus.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=395,
)


_FILECONTENTS = _descriptor.Descriptor(
  name='FileContents',
  full_name='MyFS.FileContents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='MyFS.FileContents.position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_number', full_name='MyFS.FileContents.block_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='MyFS.FileContents.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=465,
)


_CLIENT2SERVER = _descriptor.Descriptor(
  name='Client2Server',
  full_name='MyFS.Client2Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MyFS.Client2Server.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login', full_name='MyFS.Client2Server.login', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestfile', full_name='MyFS.Client2Server.requestfile', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='listdir', full_name='MyFS.Client2Server.listdir', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=616,
)


_SERVER2CLIENT = _descriptor.Descriptor(
  name='Server2Client',
  full_name='MyFS.Server2Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MyFS.Server2Client.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loginresp', full_name='MyFS.Server2Client.loginresp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestfilestatus', full_name='MyFS.Server2Client.requestfilestatus', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filecontents', full_name='MyFS.Server2Client.filecontents', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='listdirresp', full_name='MyFS.Server2Client.listdirresp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=837,
)

_DIRENTRY.fields_by_name['type'].enum_type = _DIRENTRYTYPE
_LISTDIRRESP.fields_by_name['entries'].message_type = _DIRENTRY
_CLIENT2SERVER.fields_by_name['type'].enum_type = _MESSAGETYPE
_CLIENT2SERVER.fields_by_name['login'].message_type = _LOGIN
_CLIENT2SERVER.fields_by_name['requestfile'].message_type = _REQUESTFILE
_CLIENT2SERVER.fields_by_name['listdir'].message_type = _LISTDIR
_SERVER2CLIENT.fields_by_name['type'].enum_type = _MESSAGETYPE
_SERVER2CLIENT.fields_by_name['loginresp'].message_type = _LOGINRESP
_SERVER2CLIENT.fields_by_name['requestfilestatus'].message_type = _REQUESTFILESTATUS
_SERVER2CLIENT.fields_by_name['filecontents'].message_type = _FILECONTENTS
_SERVER2CLIENT.fields_by_name['listdirresp'].message_type = _LISTDIRRESP
DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginResp'] = _LOGINRESP
DESCRIPTOR.message_types_by_name['ListDir'] = _LISTDIR
DESCRIPTOR.message_types_by_name['DirEntry'] = _DIRENTRY
DESCRIPTOR.message_types_by_name['ListDirResp'] = _LISTDIRRESP
DESCRIPTOR.message_types_by_name['RequestFile'] = _REQUESTFILE
DESCRIPTOR.message_types_by_name['RequestFileStatus'] = _REQUESTFILESTATUS
DESCRIPTOR.message_types_by_name['FileContents'] = _FILECONTENTS
DESCRIPTOR.message_types_by_name['Client2Server'] = _CLIENT2SERVER
DESCRIPTOR.message_types_by_name['Server2Client'] = _SERVER2CLIENT
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
DESCRIPTOR.enum_types_by_name['DirEntryType'] = _DIRENTRYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.Login)
  })
_sym_db.RegisterMessage(Login)

LoginResp = _reflection.GeneratedProtocolMessageType('LoginResp', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESP,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.LoginResp)
  })
_sym_db.RegisterMessage(LoginResp)

ListDir = _reflection.GeneratedProtocolMessageType('ListDir', (_message.Message,), {
  'DESCRIPTOR' : _LISTDIR,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.ListDir)
  })
_sym_db.RegisterMessage(ListDir)

DirEntry = _reflection.GeneratedProtocolMessageType('DirEntry', (_message.Message,), {
  'DESCRIPTOR' : _DIRENTRY,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.DirEntry)
  })
_sym_db.RegisterMessage(DirEntry)

ListDirResp = _reflection.GeneratedProtocolMessageType('ListDirResp', (_message.Message,), {
  'DESCRIPTOR' : _LISTDIRRESP,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.ListDirResp)
  })
_sym_db.RegisterMessage(ListDirResp)

RequestFile = _reflection.GeneratedProtocolMessageType('RequestFile', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFILE,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.RequestFile)
  })
_sym_db.RegisterMessage(RequestFile)

RequestFileStatus = _reflection.GeneratedProtocolMessageType('RequestFileStatus', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFILESTATUS,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.RequestFileStatus)
  })
_sym_db.RegisterMessage(RequestFileStatus)

FileContents = _reflection.GeneratedProtocolMessageType('FileContents', (_message.Message,), {
  'DESCRIPTOR' : _FILECONTENTS,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.FileContents)
  })
_sym_db.RegisterMessage(FileContents)

Client2Server = _reflection.GeneratedProtocolMessageType('Client2Server', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT2SERVER,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.Client2Server)
  })
_sym_db.RegisterMessage(Client2Server)

Server2Client = _reflection.GeneratedProtocolMessageType('Server2Client', (_message.Message,), {
  'DESCRIPTOR' : _SERVER2CLIENT,
  '__module__' : 'MyFS_pb2'
  # @@protoc_insertion_point(class_scope:MyFS.Server2Client)
  })
_sym_db.RegisterMessage(Server2Client)


# @@protoc_insertion_point(module_scope)
