#!/bin/sh

if [ -f /etc/system-release-cpe ] ; then
    pf=fedora-$(awk -F: '/^cpe/ {print $5}' /etc/system-release-cpe)
elif [ -f /etc/lsb-release ] ; then
    . /etc/lsb-release
    pf=ubuntu-$DISTRIB_RELEASE
elif [ -f /etc/os-release ] ; then
    if grep -q ID=debian /etc/os-release ; then
        . /etc/os-release
        pf=chrome-deb-$VERSION_ID
    else
        echo os-release-unknown
    fi
else
    pf=unknown
fi
if [ -f /.dockerenv ] ; then
    pf=${pf}-docker
fi
if [ "x$1" = x-e ] ; then
    echo PFKARCH=$pf
else
    echo $pf
fi

exit 0
