#!/bin/sh

crf=28

infile="$1"
outfile="${infile%.wmv}.mp4"

rm -f $outfile

ffmpeg \
-i "$infile" \
-strict experimental \
-c:v libx264 \
-preset fast \
-crf $crf \
-c:a aac \
-copyts \
"$outfile"

ls -l "$infile" "$outfile"

exit 0
