#!/bin/sh

if [ $# -lt 1 ] ; then
   echo usage: emacsn NUMBER files
   exit 1
fi

export EMACS_NUMBER=$1
echo export EMACS_NUMBER=$1

shift

export EMACSCLIENT_SOCKET=/tmp/$USER/emacs-$EMACS_NUMBER/server
echo export EMACSCLIENT_SOCKET=/tmp/$USER/emacs-$EMACS_NUMBER/server

emacs $* &

exit 0
