#!/bin/bash

eval `git root -v`
if [[ "x$gr" == "x" ]] ; then
    echo not in a git repo 1>&2
    exit 1
fi

cd $gr

# NOTE this does not support nested submodules.

if [[ "x$1" != "x-s" ]] ; then
    gitargs="ls-files -m"
else
    gitargs="diff --cached --name-only"
fi

# pipe output to 'cat' to prevent invocation of $PAGER
git $gitargs | cat

git submodule status | while read line ; do
    IFS=" "
    set -- $line
    cd $gr/$2
    git $gitargs | sed -e s,^,$2/,
done

exit 0
