#!/bin/bash

last_modified=2026-04-11.11:07:20

# Local Variables:
# mode: shell-script
# indent-tabs-mode: nil
# tab-width: 8
# eval: (add-hook 'write-file-functions 'time-stamp)
# time-stamp-start: "last_modified="
# time-stamp-format: "%:y-%02m-%02d.%02H:%02M:%02S"
# time-stamp-end: "$"
# End:

# rel path to file in question, relative to root of this repo
rp="$(git rev-parse --show-prefix)"

# output file
op="${fp}.orig"

set -x
echo git show HEAD:$rp ">" $op
git show HEAD:$rp > $op

exit 0
