#!/bin/bash

if [ $# -eq 0 ] ; then
    if [ -f cscope.dirs ] ; then
	dirs=$(cat cscope.dirs)
    else
	dirs="."
    fi
else
    dirs="$*"
fi

find $dirs -type f -a \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' -o -name '*.h' -o -name '*.hxx' -o -name '*.H' \) -a -size -1000000c | sort > cscope.files
cscope -bk

exit 0
