#!/bin/sh

found=0
while [ $found -eq 0 ] ; do
    if [ -f cscope.out ] ; then
	found=1
    else
	cd ..
	if [ $PWD = "/" ] ; then
	    echo no cscope.out found
	    echo hit enter
	    read crap
	    exit 1
	fi
    fi
done

echo old cscope.out:
ls -l cscope.out
rm -f cscope.out
cscope -bk
echo new cscope.out:
ls -l cscope.out
sleep 2
exit 0
