#!/bin/sh

# TODO : parse a "-g" (geometry) cmdline arg and a "-e" (execute)
#        cmd line arg and translate to the respective program's
#        favorite syntax

IFS=":"
result=""

srch() {
    for f in $PATH ; do
	if [ -f $f/$1 ] ; then
	    result="$f/$1"
	    return 0
	fi
    done
    return 1
}

if srch urxvt ; then
    exec $result "$@"
elif srch rxvt ; then
    exec $result "$@"
elif srch xfce4-terminal ; then
    exec $result  --disable-server "$@" > /dev/null 2>&1
elif srch gnome-terminal ; then
    exec $result  --disable-factory "$@" > /dev/null 2>&1
elif srch xterm ; then
    exec $result "$@" > /dev/null 2>&1
else
    echo NO TERMINAL FOUND
    exit 1
fi

exit 0
