#!/bin/sh

IFS=":"
result=""

srch() {
    for f in $PATH ; do
	if [ -f $f/$1 ] ; then
	    result="$f/$1"
	    return 0
	fi
    done
    return 1
}

if srch xfce4-terminal ; then
    exec xfce4-terminal  --disable-server "$@" > /dev/null 2>&1
elif srch gnome-terminal ; then
    exec gnome-terminal  --disable-factory "$@" > /dev/null 2>&1
elif srch xterm ; then
    exec xterm "$@" > /dev/null 2>&1
else
    echo NO TERMINAL FOUND
    exit 1
fi

exit 0
