
#ifndef __MAGIC_H__
#define __MAGIC_H__

#define Config_Add_Listen_Port_Magic           0x78683374
#define Config_Add_Listen_Port_Reply_Magic     0xaca22342
#define Config_Delete_Listen_Port_Magic        0x6004a65f
#define Config_Delete_Listen_Port_Reply_Magic  0xf75b2e1f
#define Config_Display_Listen_Ports_Magic      0x7c245a82
#define Config_Display_Proxy_Ports_Magic       0xe8635033

#endif /* __MAGIC_H__ */
